# Site settings
title: Spree Navigator
email: dfreerksen@gmail.com
description: spree_navigator is an extension for Spree to allow you to create dynamic menu items without modifying view files.
baseurl: ""
url: "http://dfreerksen.github.io/spree_navigator"

# Build settings
markdown: kramdown

# SASS/SCSS
sass:
  sass_dir: _scss
  style: :compressed
